2025-06-17 15:17:57,925 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Tue, 17 Jun 2025 15:17:57 +0000. Up 7.56 seconds.
2025-06-17 15:17:57,925 - main.py[DEBUG]: No kernel command line url found.
2025-06-17 15:17:57,925 - main.py[DEBUG]: Closing stdin.
2025-06-17 15:17:57,926 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2025-06-17 15:17:57,927 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2025-06-17 15:17:57,927 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2025-06-17 15:17:57,928 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2025-06-17 15:17:57,928 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2025-06-17 15:17:57,929 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2025-06-17 15:17:57,929 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2025-06-17 15:17:57,930 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-06-17 15:17:57,939 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2025-06-17 15:17:57,940 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2025-06-17 15:17:57,949 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-06-17 15:17:57,960 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2025-06-17 15:17:57,960 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2025-06-17 15:17:57,961 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2025-06-17 15:17:57,961 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2025-06-17 15:17:57,962 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-06-17 15:17:57,963 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2025-06-17 15:17:57,963 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2025-06-17 15:17:57,964 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2025-06-17 15:17:57,964 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2025-06-17 15:17:57,964 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2025-06-17 15:17:57,965 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2025-06-17 15:17:57,966 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 15:17:57,994 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 15:17:57,998 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2025-06-17 15:17:58,003 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2025-06-17 15:17:58,003 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-06-17 15:17:58,003 - stages.py[DEBUG]: no cache found
2025-06-17 15:17:58,003 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2025-06-17 15:17:58,003 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-06-17 15:17:58,008 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-06-17 15:17:58,008 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2025-06-17 15:17:58,012 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2025-06-17 15:17:58,012 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2025-06-17 15:17:58,012 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2025-06-17 15:17:58,012 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2025-06-17 15:17:58,012 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2025-06-17 15:17:58,012 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2025-06-17 15:17:58,012 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2025-06-17 15:17:58,012 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2025-06-17 15:17:58,012 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2025-06-17 15:17:58,012 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2025-06-17 15:17:58,013 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2025-06-17 15:17:58,013 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2025-06-17 15:17:58,013 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2025-06-17 15:17:58,013 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2025-06-17 15:17:58,013 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2025-06-17 15:17:58,017 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2025-06-17 15:17:58,054 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2025-06-17 15:17:58,054 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2025-06-17 15:17:58,054 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,056 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-06-17 15:17:58,056 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2025-06-17 15:17:58,056 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,058 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2066b) after 1 attempts
2025-06-17 15:17:58,058 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,060 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 318b) after 1 attempts
2025-06-17 15:17:58,060 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,062 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2025-06-17 15:17:58,062 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,063 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2025-06-17 15:17:58,064 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,065 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2025-06-17 15:17:58,065 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,067 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2025-06-17 15:17:58,067 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,068 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2025-06-17 15:17:58,069 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,070 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2025-06-17 15:17:58,070 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,072 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2025-06-17 15:17:58,072 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,073 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2025-06-17 15:17:58,074 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,075 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 227b) after 1 attempts
2025-06-17 15:17:58,075 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,077 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2025-06-17 15:17:58,077 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,078 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2025-06-17 15:17:58,079 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,080 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2025-06-17 15:17:58,080 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,082 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2025-06-17 15:17:58,082 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,084 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2025-06-17 15:17:58,084 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,085 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2025-06-17 15:17:58,086 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,087 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2025-06-17 15:17:58,087 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,089 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2025-06-17 15:17:58,089 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,091 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/ (200, 230b) after 1 attempts
2025-06-17 15:17:58,091 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,093 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/ipv4-associations/ (200, 13b) after 1 attempts
2025-06-17 15:17:58,093 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/ipv4-associations/3.142.142.127' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/ipv4-associations/3.142.142.127', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,095 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/ipv4-associations/3.142.142.127 (200, 13b) after 1 attempts
2025-06-17 15:17:58,095 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,096 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/device-number (200, 1b) after 1 attempts
2025-06-17 15:17:58,097 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,098 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/interface-id (200, 21b) after 1 attempts
2025-06-17 15:17:58,098 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,100 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/local-hostname (200, 43b) after 1 attempts
2025-06-17 15:17:58,100 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,102 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/local-ipv4s (200, 13b) after 1 attempts
2025-06-17 15:17:58,102 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,104 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/mac (200, 17b) after 1 attempts
2025-06-17 15:17:58,104 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,106 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/owner-id (200, 12b) after 1 attempts
2025-06-17 15:17:58,106 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,108 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/public-hostname (200, 49b) after 1 attempts
2025-06-17 15:17:58,108 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,109 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/public-ipv4s (200, 13b) after 1 attempts
2025-06-17 15:17:58,109 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,111 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/security-group-ids (200, 41b) after 1 attempts
2025-06-17 15:17:58,111 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,113 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/security-groups (200, 91b) after 1 attempts
2025-06-17 15:17:58,113 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,115 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/subnet-id (200, 24b) after 1 attempts
2025-06-17 15:17:58,115 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,116 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
2025-06-17 15:17:58,116 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,118 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/vpc-id (200, 21b) after 1 attempts
2025-06-17 15:17:58,118 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,120 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2025-06-17 15:17:58,120 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,121 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:b7:9a:fc:d4:8f/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2025-06-17 15:17:58,122 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,123 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2025-06-17 15:17:58,123 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,125 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2025-06-17 15:17:58,125 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,127 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2025-06-17 15:17:58,127 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,129 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 9b) after 1 attempts
2025-06-17 15:17:58,129 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,130 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-keys/ (200, 8b) after 1 attempts
2025-06-17 15:17:58,131 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,132 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key (200, 388b) after 1 attempts
2025-06-17 15:17:58,133 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,134 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2025-06-17 15:17:58,134 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,136 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2025-06-17 15:17:58,136 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,138 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2025-06-17 15:17:58,138 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,139 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2025-06-17 15:17:58,140 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,141 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2025-06-17 15:17:58,141 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,143 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2025-06-17 15:17:58,143 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,145 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 43b) after 1 attempts
2025-06-17 15:17:58,145 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,147 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2025-06-17 15:17:58,147 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,148 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-06-17 15:17:58,148 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,150 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2025-06-17 15:17:58,150 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,152 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 9b) after 1 attempts
2025-06-17 15:17:58,152 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,154 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 43b) after 1 attempts
2025-06-17 15:17:58,154 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,156 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 13b) after 1 attempts
2025-06-17 15:17:58,156 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,158 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2025-06-17 15:17:58,158 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,159 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2025-06-17 15:17:58,159 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,161 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 49b) after 1 attempts
2025-06-17 15:17:58,161 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,163 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 13b) after 1 attempts
2025-06-17 15:17:58,163 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,164 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2025-06-17 15:17:58,164 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,166 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 91b) after 1 attempts
2025-06-17 15:17:58,166 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,167 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2025-06-17 15:17:58,168 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,169 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 478b) after 1 attempts
2025-06-17 15:17:58,169 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,171 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1175b) after 1 attempts
2025-06-17 15:17:58,171 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,172 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1495b) after 1 attempts
2025-06-17 15:17:58,172 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-06-17 15:17:58,174 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2025-06-17 15:17:58,174 - util.py[DEBUG]: Crawl of metadata service took 0.162 seconds
2025-06-17 15:17:58,176 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2025-06-17 15:17:58,177 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2025-06-17 15:17:58,177 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2025-06-17 15:17:58,178 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2025-06-17 15:17:58,178 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpmf6ichrs) - w: [600] 12994 bytes/chars
2025-06-17 15:17:58,179 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmplvqi922f) - w: [644] 8889 bytes/chars
2025-06-17 15:17:58,179 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2025-06-17 15:17:58,179 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2025-06-17 15:17:58,180 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-17 15:17:58,180 - util.py[DEBUG]: Read 2639 bytes from /etc/cloud/cloud.cfg
2025-06-17 15:17:58,180 - util.py[DEBUG]: Attempting to load yaml from string of length 2639 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,186 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-06-17 15:17:58,186 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-06-17 15:17:58,186 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,187 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-06-17 15:17:58,187 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-06-17 15:17:58,187 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,189 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-17 15:17:58,189 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-17 15:17:58,189 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,191 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-06-17 15:17:58,191 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-06-17 15:17:58,192 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,193 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-17 15:17:58,193 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,193 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-17 15:17:58,193 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-06-17 15:17:58,193 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-09d33090ba9244295'
2025-06-17 15:17:58,204 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295 (recursive=True)
2025-06-17 15:17:58,208 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/handlers (recursive=False)
2025-06-17 15:17:58,210 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295 (recursive=True)
2025-06-17 15:17:58,214 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/scripts (recursive=False)
2025-06-17 15:17:58,217 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295 (recursive=True)
2025-06-17 15:17:58,222 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem (recursive=False)
2025-06-17 15:17:58,222 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-09d33090ba9244295/datasource (quiet=False)
2025-06-17 15:17:58,222 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/datasource - wb: [644] 29 bytes
2025-06-17 15:17:58,223 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/datasource (recursive=False)
2025-06-17 15:17:58,224 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/datasource (recursive=False)
2025-06-17 15:17:58,224 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2025-06-17 15:17:58,224 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2025-06-17 15:17:58,225 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2025-06-17 15:17:58,225 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2025-06-17 15:17:58,225 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2025-06-17 15:17:58,225 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2025-06-17 15:17:58,226 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2025-06-17 15:17:58,226 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2025-06-17 15:17:58,227 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2025-06-17 15:17:58,227 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2025-06-17 15:17:58,227 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2025-06-17 15:17:58,228 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2025-06-17 15:17:58,228 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2025-06-17 15:17:58,229 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2025-06-17 15:17:58,229 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12726 bytes
2025-06-17 15:17:58,230 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/obj.pkl (recursive=False)
2025-06-17 15:17:58,230 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/obj.pkl (recursive=False)
2025-06-17 15:17:58,231 - main.py[DEBUG]: [net] init will now be targeting instance id: i-09d33090ba9244295. new=True
2025-06-17 15:17:58,231 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-17 15:17:58,231 - util.py[DEBUG]: Read 2639 bytes from /etc/cloud/cloud.cfg
2025-06-17 15:17:58,231 - util.py[DEBUG]: Attempting to load yaml from string of length 2639 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,238 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-06-17 15:17:58,238 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-06-17 15:17:58,238 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,239 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-06-17 15:17:58,239 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-06-17 15:17:58,239 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,240 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-17 15:17:58,240 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-17 15:17:58,240 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,243 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-06-17 15:17:58,243 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-06-17 15:17:58,243 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,244 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-17 15:17:58,244 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,244 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-17 15:17:58,245 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-06-17 15:17:58,245 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2025-06-17 15:17:58,245 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-06-17 15:17:58,245 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-06-17 15:17:58,246 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2025-06-17 15:17:58,246 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/name_assign_type
2025-06-17 15:17:58,246 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-06-17 15:17:58,246 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-06-17 15:17:58,246 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2025-06-17 15:17:58,246 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/carrier
2025-06-17 15:17:58,246 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-06-17 15:17:58,246 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2025-06-17 15:17:58,246 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-06-17 15:17:58,246 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2025-06-17 15:17:58,246 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-06-17 15:17:58,246 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2025-06-17 15:17:58,246 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2025-06-17 15:17:58,246 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-06-17 15:17:58,246 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2025-06-17 15:17:58,246 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/addr_assign_type
2025-06-17 15:17:58,246 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2025-06-17 15:17:58,246 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens5/uevent
2025-06-17 15:17:58,247 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-06-17 15:17:58,247 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-06-17 15:17:58,247 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-06-17 15:17:58,247 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens5/device/device
2025-06-17 15:17:58,247 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-06-17 15:17:58,247 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2025-06-17 15:17:58,247 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2025-06-17 15:17:58,247 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/type
2025-06-17 15:17:58,247 - stages.py[DEBUG]: network config disabled by system_cfg
2025-06-17 15:17:58,247 - stages.py[INFO]: network config is disabled by system_cfg
2025-06-17 15:17:58,247 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2025-06-17 15:17:58,247 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2025-06-17 15:17:58,247 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/user-data.txt - wb: [600] 2066 bytes
2025-06-17 15:17:58,248 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/user-data.txt (recursive=False)
2025-06-17 15:17:58,249 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/user-data.txt (recursive=False)
2025-06-17 15:17:58,252 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/user-data.txt.i - wb: [600] 2244 bytes
2025-06-17 15:17:58,252 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/user-data.txt.i (recursive=False)
2025-06-17 15:17:58,253 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/user-data.txt.i (recursive=False)
2025-06-17 15:17:58,253 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/vendor-data.txt - wb: [600] 0 bytes
2025-06-17 15:17:58,254 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/vendor-data.txt (recursive=False)
2025-06-17 15:17:58,254 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/vendor-data.txt (recursive=False)
2025-06-17 15:17:58,255 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/vendor-data.txt.i - wb: [600] 308 bytes
2025-06-17 15:17:58,256 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/vendor-data.txt.i (recursive=False)
2025-06-17 15:17:58,256 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/vendor-data.txt.i (recursive=False)
2025-06-17 15:17:58,257 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/vendor-data2.txt - wb: [600] 0 bytes
2025-06-17 15:17:58,259 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/vendor-data2.txt (recursive=False)
2025-06-17 15:17:58,259 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/vendor-data2.txt (recursive=False)
2025-06-17 15:17:58,260 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/vendor-data2.txt.i - wb: [600] 308 bytes
2025-06-17 15:17:58,261 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/vendor-data2.txt.i (recursive=False)
2025-06-17 15:17:58,262 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/vendor-data2.txt.i (recursive=False)
2025-06-17 15:17:58,262 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-06-17 15:17:58,263 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-31-163.us-east-2.compute.internal (ip-172-31-31-163)
2025-06-17 15:17:58,263 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-31-163.us-east-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 15:17:58,372 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-31-163.us-east-2.compute.internal
2025-06-17 15:17:58,372 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-31-163.us-east-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 15:17:58,378 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmp25npjo_8) - w: [644] 92 bytes/chars
2025-06-17 15:17:58,378 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/consume_data - wb: [644] 25 bytes
2025-06-17 15:17:58,379 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/consume_data (recursive=False)
2025-06-17 15:17:58,380 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/consume_data (recursive=False)
2025-06-17 15:17:58,381 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/consume_data'>)
2025-06-17 15:17:58,381 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2025-06-17 15:17:58,381 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2025-06-17 15:17:58,382 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2025-06-17 15:17:58,382 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2025-06-17 15:17:58,382 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2025-06-17 15:17:58,382 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2025-06-17 15:17:58,382 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2025-06-17 15:17:58,382 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2025-06-17 15:17:58,382 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2025-06-17 15:17:58,382 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2025-06-17 15:17:58,382 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2025-06-17 15:17:58,382 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2025-06-17 15:17:58,382 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2025-06-17 15:17:58,382 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2025-06-17 15:17:58,382 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2025-06-17 15:17:58,382 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2025-06-17 15:17:58,383 - __init__.py[DEBUG]: {'Content-Type': 'application/node.eks.aws', 'Content-Disposition': 'attachment; filename="part-001"'}
2025-06-17 15:17:58,384 - __init__.py[WARNING]: Unhandled unknown content-type (application/node.eks.aws) userdata: 'b'---'...'
2025-06-17 15:17:58,384 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2025-06-17 15:17:58,386 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/cloud-config.txt - wb: [600] 0 bytes
2025-06-17 15:17:58,387 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/cloud-config.txt (recursive=False)
2025-06-17 15:17:58,388 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/cloud-config.txt (recursive=False)
2025-06-17 15:17:58,388 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2025-06-17 15:17:58,388 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2025-06-17 15:17:58,388 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2025-06-17 15:17:58,388 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2025-06-17 15:17:58,388 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2025-06-17 15:17:58,388 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2025-06-17 15:17:58,389 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2025-06-17 15:17:58,389 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2025-06-17 15:17:58,389 - stages.py[DEBUG]: no vendordata from datasource
2025-06-17 15:17:58,389 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2025-06-17 15:17:58,389 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2025-06-17 15:17:58,389 - stages.py[DEBUG]: no vendordata2 from datasource
2025-06-17 15:17:58,389 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2025-06-17 15:17:58,389 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-17 15:17:58,389 - util.py[DEBUG]: Read 2639 bytes from /etc/cloud/cloud.cfg
2025-06-17 15:17:58,389 - util.py[DEBUG]: Attempting to load yaml from string of length 2639 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,396 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-06-17 15:17:58,396 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-06-17 15:17:58,396 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,397 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-06-17 15:17:58,397 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-06-17 15:17:58,397 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,399 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-17 15:17:58,399 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-17 15:17:58,399 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,402 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-06-17 15:17:58,402 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-06-17 15:17:58,402 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,403 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-17 15:17:58,404 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,404 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-17 15:17:58,404 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-17 15:17:58,404 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-17 15:17:58,404 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,404 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-17 15:17:58,404 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,405 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,476 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-17 15:17:58,476 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-17 15:17:58,477 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-17 15:17:58,477 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-17 15:17:58,479 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2025-06-17 15:17:58,479 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16559 bytes
2025-06-17 15:17:58,481 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/obj.pkl (recursive=False)
2025-06-17 15:17:58,482 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/obj.pkl (recursive=False)
2025-06-17 15:17:58,483 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2025-06-17 15:17:58,483 - main.py[DEBUG]: no di_report found in config.
2025-06-17 15:17:58,485 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,485 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,489 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,489 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,492 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,492 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,495 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,495 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,497 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,497 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,500 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,500 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,502 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,503 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,507 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,508 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,510 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,510 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,513 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,513 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,515 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,515 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,517 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,517 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,519 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,520 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,522 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,522 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,525 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,525 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,528 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:58,528 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:58,530 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-06-17 15:17:58,530 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2025-06-17 15:17:58,531 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2025-06-17 15:17:58,531 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f781d36c9a0>)
2025-06-17 15:17:58,531 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2025-06-17 15:17:58,531 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2025-06-17 15:17:58,531 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2025-06-17 15:17:58,531 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2025-06-17 15:17:58,531 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_seed_random - wb: [644] 25 bytes
2025-06-17 15:17:58,532 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_seed_random (recursive=False)
2025-06-17 15:17:58,533 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_seed_random (recursive=False)
2025-06-17 15:17:58,533 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_seed_random'>)
2025-06-17 15:17:58,533 - cc_seed_random.py[DEBUG]: no command provided
2025-06-17 15:17:58,533 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2025-06-17 15:17:58,533 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2025-06-17 15:17:58,533 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2025-06-17 15:17:58,533 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f781d36c9a0>)
2025-06-17 15:17:58,533 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2025-06-17 15:17:58,533 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2025-06-17 15:17:58,533 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2025-06-17 15:17:58,534 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2025-06-17 15:17:58,534 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_write_files - wb: [644] 25 bytes
2025-06-17 15:17:58,534 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_write_files (recursive=False)
2025-06-17 15:17:58,535 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_write_files (recursive=False)
2025-06-17 15:17:58,535 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_write_files'>)
2025-06-17 15:17:58,535 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2025-06-17 15:17:58,535 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2025-06-17 15:17:58,535 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2025-06-17 15:17:58,536 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2025-06-17 15:17:58,536 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_write_metadata - wb: [644] 25 bytes
2025-06-17 15:17:58,536 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_write_metadata (recursive=False)
2025-06-17 15:17:58,537 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_write_metadata (recursive=False)
2025-06-17 15:17:58,537 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_write_metadata'>)
2025-06-17 15:17:58,537 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 9 bytes
2025-06-17 15:17:58,539 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2025-06-17 15:17:58,540 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2025-06-17 15:17:58,540 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2025-06-17 15:17:58,540 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2025-06-17 15:17:58,541 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2025-06-17 15:17:58,541 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2025-06-17 15:17:58,541 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2025-06-17 15:17:58,541 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2025-06-17 15:17:58,541 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2025-06-17 15:17:58,542 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2025-06-17 15:17:58,542 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f781d36cbb0>)
2025-06-17 15:17:58,542 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2025-06-17 15:17:58,542 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 15:17:58,551 - util.py[DEBUG]: Reading from /proc/1467/mountinfo (quiet=False)
2025-06-17 15:17:58,551 - util.py[DEBUG]: Read 2927 bytes from /proc/1467/mountinfo
2025-06-17 15:17:58,551 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2025-06-17 15:17:58,551 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
2025-06-17 15:17:58,552 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2025-06-17 15:17:58,552 - util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2025-06-17 15:17:58,553 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 15:17:58,714 - util.py[DEBUG]: resize_devices took 0.164 seconds
2025-06-17 15:17:58,715 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2025-06-17 15:17:58,715 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2025-06-17 15:17:58,715 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2025-06-17 15:17:58,715 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2025-06-17 15:17:58,716 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f781d36c9a0>)
2025-06-17 15:17:58,716 - util.py[DEBUG]: Reading from /proc/1467/mountinfo (quiet=False)
2025-06-17 15:17:58,717 - util.py[DEBUG]: Read 2927 bytes from /proc/1467/mountinfo
2025-06-17 15:17:58,717 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
2025-06-17 15:17:58,717 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2025-06-17 15:17:58,719 - util.py[DEBUG]: Forked child 1505 who will run callback log_time
2025-06-17 15:17:58,720 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2025-06-17 15:17:58,720 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2025-06-17 15:17:58,721 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2025-06-17 15:17:58,721 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2025-06-17 15:17:58,725 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2025-06-17 15:17:58,726 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_disk_setup - wb: [644] 25 bytes
2025-06-17 15:17:58,730 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_disk_setup (recursive=False)
2025-06-17 15:17:58,732 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_disk_setup (recursive=False)
2025-06-17 15:17:58,733 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_disk_setup'>)
2025-06-17 15:17:58,733 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2025-06-17 15:17:58,735 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2025-06-17 15:17:58,735 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2025-06-17 15:17:58,735 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_mounts - wb: [644] 25 bytes
2025-06-17 15:17:58,736 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_mounts (recursive=False)
2025-06-17 15:17:58,737 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_mounts (recursive=False)
2025-06-17 15:17:58,737 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_mounts'>)
2025-06-17 15:17:58,737 - cc_mounts.py[DEBUG]: mounts configuration is []
2025-06-17 15:17:58,738 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2025-06-17 15:17:58,738 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2025-06-17 15:17:58,738 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2025-06-17 15:17:58,738 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2025-06-17 15:17:58,738 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2025-06-17 15:17:58,738 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2025-06-17 15:17:58,738 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2025-06-17 15:17:58,738 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2025-06-17 15:17:58,738 - cc_mounts.py[DEBUG]: changed default device swap => None
2025-06-17 15:17:58,738 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2025-06-17 15:17:58,738 - cc_mounts.py[DEBUG]: no need to setup swap
2025-06-17 15:17:58,738 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2025-06-17 15:17:58,738 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2025-06-17 15:17:58,738 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2025-06-17 15:17:58,738 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2025-06-17 15:17:58,739 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f781d36cbb0>)
2025-06-17 15:17:58,741 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2025-06-17 15:17:58,741 - util.py[DEBUG]: Read 92 bytes from /var/lib/cloud/data/set-hostname
2025-06-17 15:17:58,741 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2025-06-17 15:17:58,741 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2025-06-17 15:17:58,741 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2025-06-17 15:17:58,741 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2025-06-17 15:17:58,741 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f781d36cc70>)
2025-06-17 15:17:58,741 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-31-163.us-east-2.compute.internal (ip-172-31-31-163)
2025-06-17 15:17:58,744 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 15:17:58,753 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-31-163.us-east-2.compute.internal in 1 files
2025-06-17 15:17:58,753 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 43 bytes
2025-06-17 15:17:58,755 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2025-06-17 15:17:58,756 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2025-06-17 15:17:58,757 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2025-06-17 15:17:58,757 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2025-06-17 15:17:58,757 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2025-06-17 15:17:58,757 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f781d36cbb0>)
2025-06-17 15:17:58,757 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2025-06-17 15:17:58,757 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2025-06-17 15:17:58,757 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2025-06-17 15:17:58,757 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2025-06-17 15:17:58,758 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ca_certs - wb: [644] 25 bytes
2025-06-17 15:17:58,758 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ca_certs (recursive=False)
2025-06-17 15:17:58,759 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ca_certs (recursive=False)
2025-06-17 15:17:58,759 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ca_certs'>)
2025-06-17 15:17:58,760 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2025-06-17 15:17:58,760 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2025-06-17 15:17:58,760 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2025-06-17 15:17:58,760 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2025-06-17 15:17:58,760 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_rsyslog - wb: [644] 24 bytes
2025-06-17 15:17:58,761 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_rsyslog (recursive=False)
2025-06-17 15:17:58,762 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_rsyslog (recursive=False)
2025-06-17 15:17:58,765 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_rsyslog'>)
2025-06-17 15:17:58,765 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2025-06-17 15:17:58,766 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2025-06-17 15:17:58,766 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2025-06-17 15:17:58,766 - util.py[DEBUG]: backgrounded Resizing took 0.046 seconds
2025-06-17 15:17:58,766 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2025-06-17 15:17:58,766 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_selinux - wb: [644] 25 bytes
2025-06-17 15:17:58,769 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_selinux (recursive=False)
2025-06-17 15:17:58,771 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_selinux (recursive=False)
2025-06-17 15:17:58,771 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_selinux'>)
2025-06-17 15:17:58,782 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2025-06-17 15:17:58,783 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2025-06-17 15:17:58,783 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2025-06-17 15:17:58,783 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2025-06-17 15:17:58,783 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2025-06-17 15:17:58,786 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2025-06-17 15:17:58,786 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2025-06-17 15:17:58,786 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2025-06-17 15:17:58,786 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_users_groups - wb: [644] 25 bytes
2025-06-17 15:17:58,787 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_users_groups (recursive=False)
2025-06-17 15:17:58,789 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_users_groups (recursive=False)
2025-06-17 15:17:58,789 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_users_groups'>)
2025-06-17 15:17:58,790 - __init__.py[INFO]: User ec2-user already exists, skipping.
2025-06-17 15:17:58,791 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 15:17:58,854 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2025-06-17 15:17:58,856 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2025-06-17 15:17:58,857 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2025-06-17 15:17:58,858 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2025-06-17 15:17:58,858 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2025-06-17 15:17:58,859 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2025-06-17 15:17:58,859 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2025-06-17 15:17:58,860 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2025-06-17 15:17:58,860 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ssh - wb: [644] 25 bytes
2025-06-17 15:17:58,861 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ssh (recursive=False)
2025-06-17 15:17:58,861 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ssh (recursive=False)
2025-06-17 15:17:58,862 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ssh'>)
2025-06-17 15:17:58,862 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 15:17:58,875 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2025-06-17 15:17:58,882 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 15:17:58,889 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2025-06-17 15:17:58,895 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2025-06-17 15:17:58,895 - util.py[DEBUG]: Read 130 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2025-06-17 15:17:58,895 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2025-06-17 15:17:58,895 - util.py[DEBUG]: Read 210 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2025-06-17 15:17:58,895 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-06-17 15:17:58,904 - util.py[DEBUG]: Read 3931 bytes from /etc/ssh/sshd_config
2025-06-17 15:17:58,906 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2025-06-17 15:17:58,907 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2025-06-17 15:17:58,908 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-06-17 15:17:58,908 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-06-17 15:17:58,908 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2025-06-17 15:17:58,908 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2025-06-17 15:17:58,908 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2025-06-17 15:17:58,908 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 388 bytes
2025-06-17 15:17:58,909 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-06-17 15:17:58,909 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-06-17 15:17:58,909 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2025-06-17 15:17:58,910 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-06-17 15:17:58,910 - util.py[DEBUG]: Read 3931 bytes from /etc/ssh/sshd_config
2025-06-17 15:17:58,911 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2025-06-17 15:17:58,912 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-06-17 15:17:58,912 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-06-17 15:17:58,912 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-06-17 15:17:58,912 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2025-06-17 15:17:58,912 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2025-06-17 15:17:58,912 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2025-06-17 15:17:58,912 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 554 bytes
2025-06-17 15:17:58,913 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-06-17 15:17:58,913 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-06-17 15:17:58,913 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2025-06-17 15:17:58,914 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2025-06-17 15:17:58,914 - main.py[DEBUG]: Ran 17 modules with 0 failures
2025-06-17 15:17:58,915 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp97hk50gm) - w: [644] 486 bytes/chars
2025-06-17 15:17:58,915 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-17 15:17:58,915 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2025-06-17 15:17:58,915 - util.py[DEBUG]: cloud-init mode 'init' took 1.090 seconds (1.09)
2025-06-17 15:17:58,915 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2025-06-17 15:17:59,626 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Tue, 17 Jun 2025 15:17:59 +0000. Up 9.21 seconds.
2025-06-17 15:17:59,629 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:59,629 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:59,634 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:59,634 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:59,639 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:59,640 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:59,643 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:59,643 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:59,646 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:59,646 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:59,650 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:59,650 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:59,653 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:59,654 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:59,657 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:59,658 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:59,661 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:59,661 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:59,664 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:17:59,664 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:17:59,666 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-06-17 15:17:59,667 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2025-06-17 15:17:59,667 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2025-06-17 15:17:59,667 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2025-06-17 15:17:59,668 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_keyboard - wb: [644] 25 bytes
2025-06-17 15:17:59,670 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_keyboard (recursive=False)
2025-06-17 15:17:59,674 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_keyboard (recursive=False)
2025-06-17 15:17:59,675 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_keyboard'>)
2025-06-17 15:17:59,675 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2025-06-17 15:17:59,675 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2025-06-17 15:17:59,675 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2025-06-17 15:17:59,676 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2025-06-17 15:17:59,676 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_locale - wb: [644] 24 bytes
2025-06-17 15:17:59,677 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_locale (recursive=False)
2025-06-17 15:17:59,678 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_locale (recursive=False)
2025-06-17 15:17:59,679 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_locale'>)
2025-06-17 15:17:59,679 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2025-06-17 15:17:59,679 - util.py[DEBUG]: Read 79 bytes from /etc/locale.conf
2025-06-17 15:17:59,679 - cc_locale.py[DEBUG]: Setting locale to C.UTF-8
2025-06-17 15:17:59,679 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2025-06-17 15:17:59,679 - util.py[DEBUG]: Read 79 bytes from /etc/locale.conf
2025-06-17 15:17:59,680 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 79 bytes
2025-06-17 15:17:59,683 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2025-06-17 15:17:59,686 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2025-06-17 15:17:59,687 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2025-06-17 15:17:59,687 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2025-06-17 15:17:59,687 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2025-06-17 15:17:59,687 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_set_passwords - wb: [644] 24 bytes
2025-06-17 15:17:59,688 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_set_passwords (recursive=False)
2025-06-17 15:17:59,690 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_set_passwords (recursive=False)
2025-06-17 15:17:59,690 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_set_passwords'>)
2025-06-17 15:17:59,690 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 15:17:59,733 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-06-17 15:17:59,734 - util.py[DEBUG]: Read 3931 bytes from /etc/ssh/sshd_config
2025-06-17 15:17:59,734 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2025-06-17 15:17:59,734 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2025-06-17 15:17:59,734 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2025-06-17 15:17:59,735 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2025-06-17 15:17:59,735 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2025-06-17 15:17:59,735 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_yum_variables - wb: [644] 25 bytes
2025-06-17 15:17:59,736 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_yum_variables (recursive=False)
2025-06-17 15:17:59,738 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_yum_variables (recursive=False)
2025-06-17 15:17:59,739 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_yum_variables'>)
2025-06-17 15:17:59,739 - cc_yum_variables.py[INFO]: handling yum-variables
2025-06-17 15:17:59,739 - cc_yum_variables.py[INFO]: cfg = {'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'cloud_final_modules': ['write-files-deferred', 'puppet', 'chef', 'mcollective', 'salt-minion', 'reset_rmc', 'refresh_rmc_and_interface', 'rightscale_userdata', 'scripts-vendor', 'scripts-per-once', 'scripts-per-boot', 'scripts-per-instance', 'scripts-user', 'ssh-authkey-fingerprints', 'keys-to-console', 'install-hotplug', 'phone-home', 'final-message', 'power-state-change'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2025-06-17 15:17:59,739 - cc_yum_variables.py[INFO]: No yum vars to delete
2025-06-17 15:17:59,739 - cc_yum_variables.py[INFO]: No yum vars to set
2025-06-17 15:17:59,739 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2025-06-17 15:17:59,739 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2025-06-17 15:17:59,740 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2025-06-17 15:17:59,740 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_yum_add_repo - wb: [644] 25 bytes
2025-06-17 15:17:59,741 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_yum_add_repo (recursive=False)
2025-06-17 15:17:59,742 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_yum_add_repo (recursive=False)
2025-06-17 15:17:59,743 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_yum_add_repo'>)
2025-06-17 15:17:59,743 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2025-06-17 15:17:59,743 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2025-06-17 15:17:59,743 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2025-06-17 15:17:59,743 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2025-06-17 15:17:59,743 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ntp - wb: [644] 25 bytes
2025-06-17 15:17:59,744 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ntp (recursive=False)
2025-06-17 15:17:59,746 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ntp (recursive=False)
2025-06-17 15:17:59,746 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ntp'>)
2025-06-17 15:17:59,746 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2025-06-17 15:17:59,746 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2025-06-17 15:17:59,746 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2025-06-17 15:17:59,747 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2025-06-17 15:17:59,747 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_timezone - wb: [644] 25 bytes
2025-06-17 15:17:59,748 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_timezone (recursive=False)
2025-06-17 15:17:59,749 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_timezone (recursive=False)
2025-06-17 15:17:59,750 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_timezone'>)
2025-06-17 15:17:59,750 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2025-06-17 15:17:59,750 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2025-06-17 15:17:59,750 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2025-06-17 15:17:59,750 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2025-06-17 15:17:59,750 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f7ebfe1f040>)
2025-06-17 15:17:59,751 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2025-06-17 15:17:59,751 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2025-06-17 15:17:59,751 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2025-06-17 15:17:59,751 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2025-06-17 15:17:59,751 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_runcmd - wb: [644] 25 bytes
2025-06-17 15:17:59,752 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_runcmd (recursive=False)
2025-06-17 15:17:59,753 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_runcmd (recursive=False)
2025-06-17 15:17:59,754 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_runcmd'>)
2025-06-17 15:17:59,754 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2025-06-17 15:17:59,754 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2025-06-17 15:17:59,754 - main.py[DEBUG]: Ran 9 modules with 0 failures
2025-06-17 15:17:59,755 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmph25hsuf8) - w: [644] 513 bytes/chars
2025-06-17 15:17:59,755 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-17 15:17:59,755 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2025-06-17 15:17:59,755 - util.py[DEBUG]: cloud-init mode 'modules' took 0.242 seconds (0.24)
2025-06-17 15:17:59,755 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2025-06-17 15:18:00,393 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Tue, 17 Jun 2025 15:18:00 +0000. Up 9.96 seconds.
2025-06-17 15:18:00,401 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,401 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,404 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,404 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,407 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,407 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,410 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,410 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,414 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,414 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,419 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,419 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,422 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,422 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,424 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,424 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,426 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,426 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,428 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,431 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,432 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,433 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,435 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,435 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,441 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,441 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,444 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,444 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,446 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,447 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,451 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,451 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,455 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-17 15:18:00,455 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-17 15:18:00,457 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-06-17 15:18:00,457 - modules.py[DEBUG]: Running module write-files-deferred (<module 'cloudinit.config.cc_write_files_deferred' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files_deferred.py'>) with frequency once-per-instance
2025-06-17 15:18:00,458 - handlers.py[DEBUG]: start: modules-final/config-write-files-deferred: running config-write-files-deferred with frequency once-per-instance
2025-06-17 15:18:00,458 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_write_files_deferred - wb: [644] 25 bytes
2025-06-17 15:18:00,460 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_write_files_deferred (recursive=False)
2025-06-17 15:18:00,466 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_write_files_deferred (recursive=False)
2025-06-17 15:18:00,467 - helpers.py[DEBUG]: Running config-write-files-deferred using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_write_files_deferred'>)
2025-06-17 15:18:00,467 - cc_write_files_deferred.py[DEBUG]: Skipping module named write-files-deferred, no deferred file defined in configuration
2025-06-17 15:18:00,467 - handlers.py[DEBUG]: finish: modules-final/config-write-files-deferred: SUCCESS: config-write-files-deferred ran successfully
2025-06-17 15:18:00,467 - modules.py[DEBUG]: Running module puppet (<module 'cloudinit.config.cc_puppet' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_puppet.py'>) with frequency once-per-instance
2025-06-17 15:18:00,467 - handlers.py[DEBUG]: start: modules-final/config-puppet: running config-puppet with frequency once-per-instance
2025-06-17 15:18:00,467 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_puppet - wb: [644] 25 bytes
2025-06-17 15:18:00,468 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_puppet (recursive=False)
2025-06-17 15:18:00,471 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_puppet (recursive=False)
2025-06-17 15:18:00,472 - helpers.py[DEBUG]: Running config-puppet using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_puppet'>)
2025-06-17 15:18:00,472 - cc_puppet.py[DEBUG]: Skipping module named puppet, no 'puppet' configuration found
2025-06-17 15:18:00,472 - handlers.py[DEBUG]: finish: modules-final/config-puppet: SUCCESS: config-puppet ran successfully
2025-06-17 15:18:00,472 - modules.py[DEBUG]: Running module chef (<module 'cloudinit.config.cc_chef' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_chef.py'>) with frequency always
2025-06-17 15:18:00,472 - handlers.py[DEBUG]: start: modules-final/config-chef: running config-chef with frequency always
2025-06-17 15:18:00,472 - helpers.py[DEBUG]: Running config-chef using lock (<cloudinit.helpers.DummyLock object at 0x7f82cd1d0340>)
2025-06-17 15:18:00,472 - cc_chef.py[DEBUG]: Skipping module named chef, no 'chef' key in configuration
2025-06-17 15:18:00,473 - handlers.py[DEBUG]: finish: modules-final/config-chef: SUCCESS: config-chef ran successfully
2025-06-17 15:18:00,473 - modules.py[DEBUG]: Running module mcollective (<module 'cloudinit.config.cc_mcollective' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mcollective.py'>) with frequency once-per-instance
2025-06-17 15:18:00,474 - handlers.py[DEBUG]: start: modules-final/config-mcollective: running config-mcollective with frequency once-per-instance
2025-06-17 15:18:00,474 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_mcollective - wb: [644] 24 bytes
2025-06-17 15:18:00,474 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_mcollective (recursive=False)
2025-06-17 15:18:00,475 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_mcollective (recursive=False)
2025-06-17 15:18:00,475 - helpers.py[DEBUG]: Running config-mcollective using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_mcollective'>)
2025-06-17 15:18:00,475 - cc_mcollective.py[DEBUG]: Skipping module named mcollective, no 'mcollective' key in configuration
2025-06-17 15:18:00,476 - handlers.py[DEBUG]: finish: modules-final/config-mcollective: SUCCESS: config-mcollective ran successfully
2025-06-17 15:18:00,476 - modules.py[DEBUG]: Running module salt-minion (<module 'cloudinit.config.cc_salt_minion' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_salt_minion.py'>) with frequency once-per-instance
2025-06-17 15:18:00,476 - handlers.py[DEBUG]: start: modules-final/config-salt-minion: running config-salt-minion with frequency once-per-instance
2025-06-17 15:18:00,476 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_salt_minion - wb: [644] 22 bytes
2025-06-17 15:18:00,476 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_salt_minion (recursive=False)
2025-06-17 15:18:00,478 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_salt_minion (recursive=False)
2025-06-17 15:18:00,478 - helpers.py[DEBUG]: Running config-salt-minion using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_salt_minion'>)
2025-06-17 15:18:00,479 - cc_salt_minion.py[DEBUG]: Skipping module named salt-minion, no 'salt_minion' key in configuration
2025-06-17 15:18:00,479 - handlers.py[DEBUG]: finish: modules-final/config-salt-minion: SUCCESS: config-salt-minion ran successfully
2025-06-17 15:18:00,479 - modules.py[DEBUG]: Running module reset_rmc (<module 'cloudinit.config.cc_reset_rmc' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_reset_rmc.py'>) with frequency once-per-instance
2025-06-17 15:18:00,479 - handlers.py[DEBUG]: start: modules-final/config-reset_rmc: running config-reset_rmc with frequency once-per-instance
2025-06-17 15:18:00,480 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_reset_rmc - wb: [644] 25 bytes
2025-06-17 15:18:00,480 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_reset_rmc (recursive=False)
2025-06-17 15:18:00,481 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_reset_rmc (recursive=False)
2025-06-17 15:18:00,482 - helpers.py[DEBUG]: Running config-reset_rmc using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_reset_rmc'>)
2025-06-17 15:18:00,482 - cc_reset_rmc.py[DEBUG]: module disabled, RSCT_PATH not present
2025-06-17 15:18:00,485 - handlers.py[DEBUG]: finish: modules-final/config-reset_rmc: SUCCESS: config-reset_rmc ran successfully
2025-06-17 15:18:00,485 - modules.py[DEBUG]: Running module refresh_rmc_and_interface (<module 'cloudinit.config.cc_refresh_rmc_and_interface' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_refresh_rmc_and_interface.py'>) with frequency always
2025-06-17 15:18:00,485 - handlers.py[DEBUG]: start: modules-final/config-refresh_rmc_and_interface: running config-refresh_rmc_and_interface with frequency always
2025-06-17 15:18:00,485 - helpers.py[DEBUG]: Running config-refresh_rmc_and_interface using lock (<cloudinit.helpers.DummyLock object at 0x7f82cd1d0340>)
2025-06-17 15:18:00,485 - cc_refresh_rmc_and_interface.py[DEBUG]: No 'rmcctrl' in path, disabled
2025-06-17 15:18:00,485 - handlers.py[DEBUG]: finish: modules-final/config-refresh_rmc_and_interface: SUCCESS: config-refresh_rmc_and_interface ran successfully
2025-06-17 15:18:00,485 - modules.py[DEBUG]: Running module rightscale_userdata (<module 'cloudinit.config.cc_rightscale_userdata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rightscale_userdata.py'>) with frequency once-per-instance
2025-06-17 15:18:00,485 - handlers.py[DEBUG]: start: modules-final/config-rightscale_userdata: running config-rightscale_userdata with frequency once-per-instance
2025-06-17 15:18:00,486 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_rightscale_userdata - wb: [644] 24 bytes
2025-06-17 15:18:00,486 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_rightscale_userdata (recursive=False)
2025-06-17 15:18:00,488 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_rightscale_userdata (recursive=False)
2025-06-17 15:18:00,493 - helpers.py[DEBUG]: Running config-rightscale_userdata using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_rightscale_userdata'>)
2025-06-17 15:18:00,493 - cc_rightscale_userdata.py[DEBUG]: Failed to get raw userdata in module rightscale_userdata
2025-06-17 15:18:00,493 - handlers.py[DEBUG]: finish: modules-final/config-rightscale_userdata: SUCCESS: config-rightscale_userdata ran successfully
2025-06-17 15:18:00,493 - modules.py[DEBUG]: Running module scripts-vendor (<module 'cloudinit.config.cc_scripts_vendor' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_vendor.py'>) with frequency once-per-instance
2025-06-17 15:18:00,493 - handlers.py[DEBUG]: start: modules-final/config-scripts-vendor: running config-scripts-vendor with frequency once-per-instance
2025-06-17 15:18:00,493 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_scripts_vendor - wb: [644] 25 bytes
2025-06-17 15:18:00,494 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_scripts_vendor (recursive=False)
2025-06-17 15:18:00,495 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_scripts_vendor (recursive=False)
2025-06-17 15:18:00,495 - helpers.py[DEBUG]: Running config-scripts-vendor using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_scripts_vendor'>)
2025-06-17 15:18:00,495 - handlers.py[DEBUG]: finish: modules-final/config-scripts-vendor: SUCCESS: config-scripts-vendor ran successfully
2025-06-17 15:18:00,495 - modules.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_per_once.py'>) with frequency once
2025-06-17 15:18:00,496 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
2025-06-17 15:18:00,496 - util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 25 bytes
2025-06-17 15:18:00,496 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem/config_scripts_per_once.once (recursive=False)
2025-06-17 15:18:00,500 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem/config_scripts_per_once.once (recursive=False)
2025-06-17 15:18:00,501 - helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
2025-06-17 15:18:00,501 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once ran successfully
2025-06-17 15:18:00,501 - modules.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_per_boot.py'>) with frequency always
2025-06-17 15:18:00,501 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-boot: running config-scripts-per-boot with frequency always
2025-06-17 15:18:00,501 - helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7f82cd1a13a0>)
2025-06-17 15:18:00,502 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-boot: SUCCESS: config-scripts-per-boot ran successfully
2025-06-17 15:18:00,502 - modules.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_per_instance.py'>) with frequency once-per-instance
2025-06-17 15:18:00,502 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-instance: running config-scripts-per-instance with frequency once-per-instance
2025-06-17 15:18:00,502 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_scripts_per_instance - wb: [644] 25 bytes
2025-06-17 15:18:00,502 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_scripts_per_instance (recursive=False)
2025-06-17 15:18:00,503 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_scripts_per_instance (recursive=False)
2025-06-17 15:18:00,504 - helpers.py[DEBUG]: Running config-scripts-per-instance using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_scripts_per_instance'>)
2025-06-17 15:18:00,504 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance ran successfully
2025-06-17 15:18:00,504 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency once-per-instance
2025-06-17 15:18:00,504 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
2025-06-17 15:18:00,504 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_scripts_user - wb: [644] 24 bytes
2025-06-17 15:18:00,508 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_scripts_user (recursive=False)
2025-06-17 15:18:00,509 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_scripts_user (recursive=False)
2025-06-17 15:18:00,509 - helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_scripts_user'>)
2025-06-17 15:18:00,509 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2025-06-17 15:18:00,510 - modules.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2025-06-17 15:18:00,510 - handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
2025-06-17 15:18:00,510 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ssh_authkey_fingerprints - wb: [644] 25 bytes
2025-06-17 15:18:00,511 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ssh_authkey_fingerprints (recursive=False)
2025-06-17 15:18:00,512 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ssh_authkey_fingerprints (recursive=False)
2025-06-17 15:18:00,512 - helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_ssh_authkey_fingerprints'>)
2025-06-17 15:18:00,512 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-06-17 15:18:00,513 - util.py[DEBUG]: Read 3931 bytes from /etc/ssh/sshd_config
2025-06-17 15:18:00,513 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2025-06-17 15:18:00,533 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2025-06-17 15:18:00,534 - util.py[DEBUG]: Read 388 bytes from /home/ec2-user/.ssh/authorized_keys
2025-06-17 15:18:00,570 - handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
2025-06-17 15:18:00,570 - modules.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2025-06-17 15:18:00,570 - handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
2025-06-17 15:18:00,570 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_keys_to_console - wb: [644] 25 bytes
2025-06-17 15:18:00,571 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_keys_to_console (recursive=False)
2025-06-17 15:18:00,571 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_keys_to_console (recursive=False)
2025-06-17 15:18:00,572 - helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_keys_to_console'>)
2025-06-17 15:18:00,572 - subp.py[DEBUG]: Running command ['/usr/libexec/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
2025-06-17 15:18:00,676 - handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
2025-06-17 15:18:00,676 - modules.py[DEBUG]: Running module install-hotplug (<module 'cloudinit.config.cc_install_hotplug' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_install_hotplug.py'>) with frequency once-per-instance
2025-06-17 15:18:00,677 - handlers.py[DEBUG]: start: modules-final/config-install-hotplug: running config-install-hotplug with frequency once-per-instance
2025-06-17 15:18:00,677 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_install_hotplug - wb: [644] 25 bytes
2025-06-17 15:18:00,678 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_install_hotplug (recursive=False)
2025-06-17 15:18:00,679 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_install_hotplug (recursive=False)
2025-06-17 15:18:00,680 - helpers.py[DEBUG]: Running config-install-hotplug using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_install_hotplug'>)
2025-06-17 15:18:00,680 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>}}
2025-06-17 15:18:00,680 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=hotplug
2025-06-17 15:18:00,680 - cc_install_hotplug.py[DEBUG]: Skipping hotplug install, not enabled
2025-06-17 15:18:00,681 - handlers.py[DEBUG]: finish: modules-final/config-install-hotplug: SUCCESS: config-install-hotplug ran successfully
2025-06-17 15:18:00,681 - modules.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_phone_home.py'>) with frequency once-per-instance
2025-06-17 15:18:00,681 - handlers.py[DEBUG]: start: modules-final/config-phone-home: running config-phone-home with frequency once-per-instance
2025-06-17 15:18:00,681 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_phone_home - wb: [644] 25 bytes
2025-06-17 15:18:00,682 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_phone_home (recursive=False)
2025-06-17 15:18:00,682 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_phone_home (recursive=False)
2025-06-17 15:18:00,683 - helpers.py[DEBUG]: Running config-phone-home using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_phone_home'>)
2025-06-17 15:18:00,683 - cc_phone_home.py[DEBUG]: Skipping module named phone-home, no 'phone_home' configuration found
2025-06-17 15:18:00,683 - handlers.py[DEBUG]: finish: modules-final/config-phone-home: SUCCESS: config-phone-home ran successfully
2025-06-17 15:18:00,683 - modules.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2025-06-17 15:18:00,683 - handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
2025-06-17 15:18:00,684 - helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7f82cd1a1c10>)
2025-06-17 15:18:00,684 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-17 15:18:00,684 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2025-06-17 15:18:00,708 - util.py[DEBUG]: Cloud-init v. 22.2.2 finished at Tue, 17 Jun 2025 15:18:00 +0000. Datasource DataSourceEc2.  Up 10.35 seconds
2025-06-17 15:18:00,708 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 52 bytes
2025-06-17 15:18:00,715 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/boot-finished (recursive=False)
2025-06-17 15:18:00,716 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/boot-finished (recursive=False)
2025-06-17 15:18:00,717 - handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
2025-06-17 15:18:00,717 - modules.py[DEBUG]: Running module power-state-change (<module 'cloudinit.config.cc_power_state_change' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_power_state_change.py'>) with frequency once-per-instance
2025-06-17 15:18:00,717 - handlers.py[DEBUG]: start: modules-final/config-power-state-change: running config-power-state-change with frequency once-per-instance
2025-06-17 15:18:00,718 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_power_state_change - wb: [644] 25 bytes
2025-06-17 15:18:00,718 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_power_state_change (recursive=False)
2025-06-17 15:18:00,720 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09d33090ba9244295/sem/config_power_state_change (recursive=False)
2025-06-17 15:18:00,720 - helpers.py[DEBUG]: Running config-power-state-change using lock (<FileLock using file '/var/lib/cloud/instances/i-09d33090ba9244295/sem/config_power_state_change'>)
2025-06-17 15:18:00,720 - util.py[DEBUG]: Reading from /proc/1554/cmdline (quiet=False)
2025-06-17 15:18:00,720 - util.py[DEBUG]: Read 58 bytes from /proc/1554/cmdline
2025-06-17 15:18:00,721 - cc_power_state_change.py[DEBUG]: After pid 1554 ends, will execute: shutdown -r now Rebooting machine to apply SELinux kernel commandline setting
2025-06-17 15:18:00,722 - util.py[DEBUG]: Forked child 1569 who will run callback run_after_pid_gone
2025-06-17 15:18:00,724 - util.py[DEBUG]: Reading from /proc/1554/cmdline (quiet=False)
2025-06-17 15:18:00,724 - handlers.py[DEBUG]: finish: modules-final/config-power-state-change: SUCCESS: config-power-state-change ran successfully
2025-06-17 15:18:00,724 - util.py[DEBUG]: Read 58 bytes from /proc/1554/cmdline
2025-06-17 15:18:00,725 - main.py[DEBUG]: Ran 19 modules with 0 failures
2025-06-17 15:18:00,726 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpjphf38c1) - w: [644] 540 bytes/chars
2025-06-17 15:18:00,727 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp8r71nb1a) - w: [644] 64 bytes/chars
2025-06-17 15:18:00,732 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-06-17 15:18:00,733 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-17 15:18:00,733 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2025-06-17 15:18:00,734 - util.py[DEBUG]: cloud-init mode 'modules' took 0.457 seconds (0.46)
2025-06-17 15:18:00,734 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
2025-06-17 15:18:01,007 - util.py[DEBUG]: Reading from /proc/1554/cmdline (quiet=False)
2025-06-17 15:18:01,008 - cc_power_state_change.py[DEBUG]: cmdline changed for 1554 [now: None]
2025-06-17 15:18:01,020 - cc_power_state_change.py[DEBUG]: check_condition command (test -f /run/cloud-init-selinux-reboot): exited 1. condition not met.
